import { StreamedSection } from "@/types"

export async function generateReview(idea: string): Promise<StreamedSection> {
  await new Promise((r) => setTimeout(r, 1300))

  return {
    stepId: "ai-review",
    title: "## AI Review\n\n",
    content: `### Quality Assessment ✅\n\n- **Architecture** — Clean separation of concerns, follows domain-driven design\n- **API Design** — RESTful, consistent naming, proper error handling\n- **Database Schema** — Normalized, indexed, scalable\n- **User Flows** — All edge cases covered, intuitive navigation\n\n### Risk Analysis\n\n| Risk | Impact | Mitigation |\n|------|--------|------------|\n| High traffic spikes | Medium | Auto-scaling + CDN |\n| Data consistency | High | Transactions + idempotency |\n| Third-party downtime | Low | Circuit breaker + fallback |\n\n### Recommendations\n\n- Add Redis caching layer for hot data\n- Implement feature flags for gradual rollout\n- Set up monitoring with OpenTelemetry\n\n---\n\n*Generated by PM Copilot v1.0 — ${idea}*\n`,
  }
}
