import { StreamedSection, Language } from "@/types"
import { getProvider, getConfig } from "@/lib/ai/providers"

const PROMPTS: Record<Language, string> = {
  en: `You are a QA lead reviewing a product spec. Provide quality assessment: ### Quality Assessment (3-4 check items), ### Risk Analysis (table: Risk, Impact, Mitigation), ### Recommendations (2-3 items). End with "---" and "*Generated by PM Copilot v1.0*". Markdown. 200-400 words. No title heading.`,
  zh: `你是一位QA负责人，审查产品规格。提供质量评估：### 质量评估（3-4条检查项），### 风险分析（表格：风险、影响、缓解措施），### 改进建议（2-3条）。以"---"和"*由 PM Copilot v1.0 生成*"结尾。Markdown格式。200-400字。不要包含标题。`,
}

export async function generateReview(idea: string, language: Language = "en"): Promise<StreamedSection> {
  const provider = getProvider()
  const config = getConfig()
  const userPrompt = language === "zh" ? `产品想法：${idea}` : idea
  const content = await provider.generate(PROMPTS[language], userPrompt, config)
  return {
    stepId: "ai-review",
    title: language === "zh" ? "## AI审查\n\n" : "## AI Review\n\n",
    content: content + "\n\n",
  }
}
