import { StreamedSection } from "@/types"
import { getProvider, getConfig } from "@/lib/ai/providers"

const SYSTEM_PROMPT = `You are a QA lead reviewing a product specification. Provide a quality assessment for the given product idea.

Include:
### Quality Assessment — 3-4 ✅ items evaluating architecture, API, database, and flows
### Risk Analysis — a Markdown table with columns: Risk, Impact, Mitigation
### Recommendations — 2-3 actionable improvements

Output: Markdown. End with "---" and "*Generated by PM Copilot v1.0*". Keep it concise (200-400 words). Do NOT include a title heading.`

export async function generateReview(idea: string): Promise<StreamedSection> {
  const provider = getProvider()
  const config = getConfig()

  const userPrompt = `Product Idea: ${idea}\n\nPlease provide a quality assessment and review for this product idea.`

  const content = await provider.generate(SYSTEM_PROMPT, userPrompt, config)

  return {
    stepId: "ai-review",
    title: "## AI Review\n\n",
    content: content + "\n\n",
  }
}
