import { MenuItem, WorkflowStep } from "@/types"

export const MENU_ITEMS: MenuItem[] = [
  { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { id: "projects", label: "Projects", icon: "FolderKanban" },
  { id: "history", label: "History", icon: "History" },
  { id: "templates", label: "Templates", icon: "FileText" },
  { id: "settings", label: "Settings", icon: "Settings" },
]

export const WORKFLOW_STEPS: Omit<WorkflowStep, "status">[] = [
  { id: "clarification", name: "Clarification" },
  { id: "requirement", name: "Requirement" },
  { id: "product-design", name: "Product Design" },
  { id: "flow", name: "Flow" },
  { id: "database", name: "Database" },
  { id: "api", name: "API" },
  { id: "test", name: "Test" },
  { id: "dev-prompt", name: "Development Prompt" },
  { id: "ai-review", name: "AI Review" },
]

export const MOCK_WORKFLOW_DATA: WorkflowStep[] = [
  { id: "clarification", name: "Clarification", status: "COMPLETED" },
  { id: "requirement", name: "Requirement", status: "COMPLETED" },
  { id: "product-design", name: "Product Design", status: "RUNNING" },
  { id: "flow", name: "Flow", status: "WAITING" },
  { id: "database", name: "Database", status: "WAITING" },
  { id: "api", name: "API", status: "WAITING" },
  { id: "test", name: "Test", status: "WAITING" },
  { id: "dev-prompt", name: "Development Prompt", status: "WAITING" },
  { id: "ai-review", name: "AI Review", status: "ERROR" },
]

export const MOCK_MARKDOWN = `# Project: AI Task Manager

## Overview

A smart task management system powered by AI to help teams organize, prioritize, and track work items efficiently.

## Core Features

### 1. Intelligent Task Creation
- **Natural language input** — describe tasks in plain English
- **Auto-categorization** — AI assigns labels and priorities
- **Smart suggestions** — recommends related tasks and dependencies

### 2. Workflow Automation
| Stage | Description | Trigger |
|-------|-------------|---------|
| Backlog | Newly created tasks | Manual / AI |
| In Progress | Work started | Developer assigns |
| Review | Code complete | PR opened |
| Done | Merged & deployed | PR merged |

### 3. AI-Powered Insights
> "The best way to predict the future is to create it." — Peter Drucker

- Sprint velocity prediction
- Bottleneck detection
- Team workload balancing

## Tech Stack

\`\`\`typescript
const stack = {
  frontend: "Next.js + TypeScript",
  styling: "Tailwind CSS",
  backend: "Node.js + Express",
  database: "PostgreSQL",
  ai: "OpenAI API",
}
\`\`\`

## API Endpoints

- \`GET /api/tasks\` — List all tasks
- \`POST /api/tasks\` — Create a new task
- \`PUT /api/tasks/:id\` — Update a task
- \`DELETE /api/tasks/:id\` — Remove a task

---

*Generated by PM Copilot v1.0*
`
