import { WorkflowStep, StreamedSection, Language } from "@/types"
import { WorkflowEngine, WorkflowStepId } from "./workflow-engine"
import { MarkdownBuilder } from "./markdown-builder"
import { ProviderError } from "./provider"
import { getProvider, getConfig } from "./providers"

const SECTION_TITLES: Record<WorkflowStepId, Record<Language, string>> = {
  clarification: { en: "## Clarification\n\n", zh: "## 需求澄清\n\n" },
  requirement: { en: "## Requirements\n\n", zh: "## 需求文档\n\n" },
  "product-design": { en: "## Product Design\n\n", zh: "## 产品设计\n\n" },
  flow: { en: "## User Flows\n\n", zh: "## 用户流程\n\n" },
  database: { en: "## Database Schema\n\n", zh: "## 数据库设计\n\n" },
  api: { en: "## API Design\n\n", zh: "## API设计\n\n" },
  test: { en: "## Test Plan\n\n", zh: "## 测试计划\n\n" },
  "dev-prompt": { en: "## Development Prompt\n\n", zh: "## 开发指南\n\n" },
  "ai-review": { en: "## AI Review\n\n", zh: "## AI审查\n\n" },
}

const SYSTEM_PROMPTS: Record<WorkflowStepId, Record<Language, string>> = {
  clarification: {
    en: `You are a senior product manager. Clarify the given product idea by asking and answering 3-5 key questions: core problem, target users, primary use cases, success metrics, constraints. Output in Markdown. 200-400 words. Do NOT include a title heading.`,
    zh: `你是一位资深产品经理。请对给定的产品想法进行澄清分析，提出并回答3-5个关键问题：核心问题、目标用户、主要使用场景、成功指标、约束条件。使用Markdown格式输出。200-400字。不要包含标题。`,
  },
  requirement: {
    en: `You are a senior product manager. Generate functional and non-functional requirements. Include: ### Functional Requirements (4-6 FR items), ### Non-Functional Requirements (3-4 items). Markdown. 200-400 words. No title heading.`,
    zh: `你是一位资深产品经理。为给定的产品想法生成功能和非功能需求。包含：### 功能需求（4-6条FR编号项），### 非功能需求（3-4条）。Markdown格式。200-400字。不要包含标题。`,
  },
  "product-design": {
    en: `You are a senior product designer. Create product design overview: ### Product Overview, ### Information Architecture (code block), ### Design Principles, ### Key Screens. Markdown. 300-500 words. No title heading.`,
    zh: `你是一位资深产品设计师。创建产品设计概述：### 产品概述，### 信息架构（代码块），### 设计原则，### 关键页面。Markdown格式。300-500字。不要包含标题。`,
  },
  flow: {
    en: `You are a UX designer. Map key user flows: ### Primary Flow (steps), ### Secondary Flows (2-3), ### Edge Cases (2-3). Markdown. 200-400 words. No title heading.`,
    zh: `你是一位UX设计师。绘制关键用户流程：### 主要流程（步骤），### 次要流程（2-3个），### 边界情况（2-3个）。Markdown格式。200-400字。不要包含标题。`,
  },
  database: {
    en: `You are a backend architect. Design database schema: ### Core Entities (table: Table, Purpose, Key Fields), ### Relationships, ### Indexes. Markdown. 200-400 words. No title heading.`,
    zh: `你是一位后端架构师。设计数据库架构：### 核心实体（表格：表名、用途、关键字段），### 实体关系，### 索引建议。Markdown格式。200-400字。不要包含标题。`,
  },
  api: {
    en: `You are an API architect. Design REST API: ### RESTful Endpoints (code block), ### Authentication, ### Response Format (JSON example). Markdown. 200-400 words. No title heading.`,
    zh: `你是一位API架构师。设计REST API：### RESTful接口（代码块），### 认证方式，### 响应格式（JSON示例）。Markdown格式。200-400字。不要包含标题。`,
  },
  test: {
    en: `You are a QA engineer. Write test plan: ### Test Cases (4-5 TC items), ### Testing Levels (Unit, Integration, E2E). Markdown. 200-400 words. No title heading.`,
    zh: `你是一位QA工程师。编写测试计划：### 测试用例（4-5条TC编号项），### 测试层级（单元、集成、E2E）。Markdown格式。200-400字。不要包含标题。`,
  },
  "dev-prompt": {
    en: `You are a tech lead. Write development prompt: ### Tech Stack, ### Getting Started (bash code block), ### Key Dependencies (3-4 packages). Markdown. 200-400 words. No title heading.`,
    zh: `你是一位技术负责人。编写开发指南：### 技术栈，### 快速开始（bash代码块），### 关键依赖（3-4个包）。Markdown格式。200-400字。不要包含标题。`,
  },
  "ai-review": {
    en: `You are a QA lead reviewing product spec: ### Quality Assessment (3-4 items), ### Risk Analysis (table), ### Recommendations (2-3 items). End with "---" and "*Generated by PM Copilot v1.0*". Markdown. 200-400 words. No title heading.`,
    zh: `你是一位QA负责人审查产品规格：### 质量评估（3-4条），### 风险分析（表格），### 改进建议（2-3条）。以"---"和"*由 PM Copilot v1.0 生成*"结尾。Markdown格式。200-400字。不要包含标题。`,
  },
}

export interface CoordinatorCallbacks {
  onStepStart: (step: WorkflowStep, steps: WorkflowStep[]) => void
  onStepComplete: (step: WorkflowStep, section: StreamedSection, allSections: StreamedSection[], allSteps: WorkflowStep[]) => void
  onStreamChunk: (stepId: WorkflowStepId, delta: string) => void
  onComplete: (allSections: StreamedSection[]) => void
  onError: (stepId: WorkflowStepId, error: Error) => void
}

export class Coordinator {
  private workflow: WorkflowEngine
  private builder: MarkdownBuilder
  private aborted = false

  constructor() {
    this.workflow = new WorkflowEngine()
    this.builder = new MarkdownBuilder()
  }

  async execute(idea: string, language: Language, callbacks: CoordinatorCallbacks): Promise<void> {
    this.workflow.reset()
    this.builder.reset()
    this.aborted = false

    const provider = getProvider()
    const config = getConfig()
    const stepIds = [...this.workflow.getStepIds()]

    for (const stepId of stepIds) {
      if (this.aborted) break

      const step = this.workflow.startCurrentStep()
      if (!step) break

      callbacks.onStepStart(step, this.workflow.getSteps())

      try {
        const systemPrompt = SYSTEM_PROMPTS[stepId]?.[language] ?? SYSTEM_PROMPTS[stepId]?.en ?? ""
        const userPrompt = language === "zh"
          ? `产品想法：${idea}`
          : `Product Idea: ${idea}`

        let streamedContent = ""
        await provider.generateStream(systemPrompt, userPrompt, config, (delta) => {
          streamedContent += delta
          callbacks.onStreamChunk(stepId, delta)
        })

        if (this.aborted) break

        const title = SECTION_TITLES[stepId]?.[language] ?? `## ${stepId}\n\n`
        const section: StreamedSection = {
          stepId,
          title,
          content: streamedContent + "\n\n",
        }

        this.builder.append(section)
        this.workflow.completeCurrentStep()
        callbacks.onStepComplete(step, section, this.builder.getSections(), this.workflow.getSteps())
      } catch (error) {
        this.workflow.markError(stepId)
        callbacks.onError(stepId, error instanceof Error ? error : new Error(String(error)))

        if (error instanceof ProviderError && error.code === "missing_key") {
          this.aborted = true
          break
        }
        // Non-fatal errors — skip without overwriting ERROR status
        this.workflow.skipCurrentStep()
      }
    }

    if (!this.aborted) {
      callbacks.onComplete(this.builder.getSections())
    }
  }

  abort(): void {
    this.aborted = true
  }
}

export const coordinator = new Coordinator()
